### PR TITLE
Update docsy theme

### PR DESCRIPTION
**Pull request by LorenzBischof**
I did some light testing and everything seems to work. We can probably merge this and slowly migrate and test the trainings.

### CODE REVIEW

**Comment by splattner** [comment]
Did you remove the "copy" button by intention?

**Comment by LorenzBischof** [comment]
Yes. That was added in Docsy 0.5.1: https://github.com/google/docsy/pull/1245 You can test the new theme by adding `replacements` in the `hugo-training-template`.

**Review by splattner — APPROVED** [review]

**Comment by LorenzBischof** [comment]
Do you need my help with testing and deploying? If not, feel free to merge.

**Comment by splattner** [comment]
I merged, do yo mind also updating and testing it in https://github.com/acend/hugo-training-template/pull/302 and https://github.com/acend/hugo-training-template/pull/301 ?
when its fine there, I think I'll be able to apply the necessary changes to all our other repos.

@schlapzz also said in our internal  chat

> Bei PR301 müsste man wohl die Color Vars anpassen (gray-X) sind im SCSS von Docsy 0.9.1 nicht mehr vorhanden... Wir haben aber in unseren SCSS z.B. docsy-acend) noch diverse Referenzen auf diese Farben.  (Siehe hier: https://github.com/acend/docsy-plus/blob/main/assets/scss/site.scss#L33)

**Comment by LorenzBischof** [comment]
`gray-300` is a bootstrap variable. I changed the implementation a bit and it should work again.

**Pull request merged**
