### PR TITLE
Rewrite hook partials

### PR DESCRIPTION
**Pull request by LorenzBischof**
- Move Go templating out of Javascript file
- Allow custom hooks for trainings
- Fingerprint locally (to invalidate local cache)

### CODE REVIEW

**Comment by phil-pona** [comment]
This change needs to be tested first on the Prometheus github.com/puzzle/prometheus-training/ @mabegglen  Kubernetes https://github.com/acend/kubernetes-basics-training @aymonc  and Cilium Training https://github.com/acend/cilium-basics-training @splattner

**Comment by mebagel** [comment]
LGTM, Prometheus Training mode-switcher still works as expected

**Comment by aymonc** [comment]
Kubernetes Basiscs Training: parameter-replace-content still works as expected

**Review by splattner — APPROVED** [review]

**Comment by splattner** [comment]
lgtm

**Pull request merged**
